<?php

namespace srag\Plugins\OnlyOffice;

use srag\Plugins\OnlyOffice\Config\Repository as ConfigRepository;
use srag\Plugins\OnlyOffice\ObjectSettings\Repository as ObjectSettingsRepository;
use srag\Plugins\OnlyOffice\Utils\OnlyOfficeTrait;
use ilOnlyOfficePlugin;
use srag\DIC\OnlyOffice\DICTrait;

/**
 * Class Repository
 *
 * Generated by SrPluginGenerator v1.3.4
 *
 * @package srag\Plugins\OnlyOffice
 *
 * @author Theodor Truffer <theo@fluxlabs.ch>
 */
final class Repository
{

    use DICTrait;
    use OnlyOfficeTrait;
    const PLUGIN_CLASS_NAME = ilOnlyOfficePlugin::class;
    protected static ?Repository $instance = null;

    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }

    private function __construct()
    {

    }

    public function config() : ConfigRepository
    {
        return ConfigRepository::getInstance();
    }

    public function dropTables(): void
    {
        $this->config()->dropTables();
        $this->objectSettings()->dropTables();
    }

    public function installTables(): void
    {
        $this->config()->installTables();
        $this->objectSettings()->installTables();
    }

    public function objectSettings() : ObjectSettingsRepository
    {
        return ObjectSettingsRepository::getInstance();
    }
}
